/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RevealMarketInterface extends ethers.utils.Interface {
  functions: {
    "BIOMEBASE_KEY()": FunctionFragment;
    "MARKET_CLOSE_COUNTDOWN_TIMESTAMP()": FunctionFragment;
    "PERLIN_LENGTH_SCALE()": FunctionFragment;
    "PERLIN_MIRROR_X()": FunctionFragment;
    "PERLIN_MIRROR_Y()": FunctionFragment;
    "PLANETHASH_KEY()": FunctionFragment;
    "SPACETYPE_KEY()": FunctionFragment;
    "bulkGetRevealRequests(uint256,uint256)": FunctionFragment;
    "claimReveal(uint256)": FunctionFragment;
    "getAllRevealRequests()": FunctionFragment;
    "getNRevealRequests()": FunctionFragment;
    "getRevealRequest(uint256)": FunctionFragment;
    "initialize(address,uint256,uint256,uint256,bool,bool,uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestReveal(uint256[2],uint256[2][2],uint256[2],uint256[9])": FunctionFragment;
    "rugPull()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BIOMEBASE_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKET_CLOSE_COUNTDOWN_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERLIN_LENGTH_SCALE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERLIN_MIRROR_X",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERLIN_MIRROR_Y",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLANETHASH_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SPACETYPE_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bulkGetRevealRequests",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRevealRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNRevealRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestReveal",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ]
  ): string;
  encodeFunctionData(functionFragment: "rugPull", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "BIOMEBASE_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKET_CLOSE_COUNTDOWN_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERLIN_LENGTH_SCALE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERLIN_MIRROR_X",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERLIN_MIRROR_Y",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLANETHASH_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SPACETYPE_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bulkGetRevealRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRevealRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNRevealRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rugPull", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "RevealCollected(address,uint256,uint256,uint256,uint256)": EventFragment;
    "RevealRequested(address,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevealCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevealRequested"): EventFragment;
}

export class RevealMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RevealMarketInterface;

  functions: {
    BIOMEBASE_KEY(overrides?: CallOverrides): Promise<[BigNumber]>;

    MARKET_CLOSE_COUNTDOWN_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    PERLIN_LENGTH_SCALE(overrides?: CallOverrides): Promise<[BigNumber]>;

    PERLIN_MIRROR_X(overrides?: CallOverrides): Promise<[boolean]>;

    PERLIN_MIRROR_Y(overrides?: CallOverrides): Promise<[boolean]>;

    PLANETHASH_KEY(overrides?: CallOverrides): Promise<[BigNumber]>;

    SPACETYPE_KEY(overrides?: CallOverrides): Promise<[BigNumber]>;

    bulkGetRevealRequests(
      startIdx: BigNumberish,
      endIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
          requester: string;
          location: BigNumber;
          x: BigNumber;
          y: BigNumber;
          value: BigNumber;
          paid: boolean;
        })[]
      ] & {
        ret: ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
          requester: string;
          location: BigNumber;
          x: BigNumber;
          y: BigNumber;
          value: BigNumber;
          paid: boolean;
        })[];
      }
    >;

    claimReveal(
      location: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllRevealRequests(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
          requester: string;
          location: BigNumber;
          x: BigNumber;
          y: BigNumber;
          value: BigNumber;
          paid: boolean;
        })[]
      ]
    >;

    getNRevealRequests(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRevealRequest(
      location: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
          requester: string;
          location: BigNumber;
          x: BigNumber;
          y: BigNumber;
          value: BigNumber;
          paid: boolean;
        }
      ]
    >;

    initialize(
      coreAddress: string,
      planetHashKey: BigNumberish,
      spacetypeKey: BigNumberish,
      biomebaseKey: BigNumberish,
      perlinMirrorX: boolean,
      perlinMirrorY: boolean,
      perlinLengthScale: BigNumberish,
      _marketClosedCountdownTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestReveal(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rugPull(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  BIOMEBASE_KEY(overrides?: CallOverrides): Promise<BigNumber>;

  MARKET_CLOSE_COUNTDOWN_TIMESTAMP(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  PERLIN_LENGTH_SCALE(overrides?: CallOverrides): Promise<BigNumber>;

  PERLIN_MIRROR_X(overrides?: CallOverrides): Promise<boolean>;

  PERLIN_MIRROR_Y(overrides?: CallOverrides): Promise<boolean>;

  PLANETHASH_KEY(overrides?: CallOverrides): Promise<BigNumber>;

  SPACETYPE_KEY(overrides?: CallOverrides): Promise<BigNumber>;

  bulkGetRevealRequests(
    startIdx: BigNumberish,
    endIdx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      requester: string;
      location: BigNumber;
      x: BigNumber;
      y: BigNumber;
      value: BigNumber;
      paid: boolean;
    })[]
  >;

  claimReveal(
    location: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllRevealRequests(
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      requester: string;
      location: BigNumber;
      x: BigNumber;
      y: BigNumber;
      value: BigNumber;
      paid: boolean;
    })[]
  >;

  getNRevealRequests(overrides?: CallOverrides): Promise<BigNumber>;

  getRevealRequest(
    location: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      requester: string;
      location: BigNumber;
      x: BigNumber;
      y: BigNumber;
      value: BigNumber;
      paid: boolean;
    }
  >;

  initialize(
    coreAddress: string,
    planetHashKey: BigNumberish,
    spacetypeKey: BigNumberish,
    biomebaseKey: BigNumberish,
    perlinMirrorX: boolean,
    perlinMirrorY: boolean,
    perlinLengthScale: BigNumberish,
    _marketClosedCountdownTimestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestReveal(
    _a: [BigNumberish, BigNumberish],
    _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
    _c: [BigNumberish, BigNumberish],
    _input: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rugPull(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BIOMEBASE_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    MARKET_CLOSE_COUNTDOWN_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PERLIN_LENGTH_SCALE(overrides?: CallOverrides): Promise<BigNumber>;

    PERLIN_MIRROR_X(overrides?: CallOverrides): Promise<boolean>;

    PERLIN_MIRROR_Y(overrides?: CallOverrides): Promise<boolean>;

    PLANETHASH_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    SPACETYPE_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    bulkGetRevealRequests(
      startIdx: BigNumberish,
      endIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        requester: string;
        location: BigNumber;
        x: BigNumber;
        y: BigNumber;
        value: BigNumber;
        paid: boolean;
      })[]
    >;

    claimReveal(
      location: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllRevealRequests(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        requester: string;
        location: BigNumber;
        x: BigNumber;
        y: BigNumber;
        value: BigNumber;
        paid: boolean;
      })[]
    >;

    getNRevealRequests(overrides?: CallOverrides): Promise<BigNumber>;

    getRevealRequest(
      location: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        requester: string;
        location: BigNumber;
        x: BigNumber;
        y: BigNumber;
        value: BigNumber;
        paid: boolean;
      }
    >;

    initialize(
      coreAddress: string,
      planetHashKey: BigNumberish,
      spacetypeKey: BigNumberish,
      biomebaseKey: BigNumberish,
      perlinMirrorX: boolean,
      perlinMirrorY: boolean,
      perlinLengthScale: BigNumberish,
      _marketClosedCountdownTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestReveal(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    rugPull(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    RevealCollected(
      collector?: null,
      loc?: null,
      x?: null,
      y?: null,
      value?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        collector: string;
        loc: BigNumber;
        x: BigNumber;
        y: BigNumber;
        value: BigNumber;
      }
    >;

    RevealRequested(
      requester?: null,
      loc?: null,
      x?: null,
      y?: null,
      value?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        requester: string;
        loc: BigNumber;
        x: BigNumber;
        y: BigNumber;
        value: BigNumber;
      }
    >;
  };

  estimateGas: {
    BIOMEBASE_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    MARKET_CLOSE_COUNTDOWN_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PERLIN_LENGTH_SCALE(overrides?: CallOverrides): Promise<BigNumber>;

    PERLIN_MIRROR_X(overrides?: CallOverrides): Promise<BigNumber>;

    PERLIN_MIRROR_Y(overrides?: CallOverrides): Promise<BigNumber>;

    PLANETHASH_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    SPACETYPE_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    bulkGetRevealRequests(
      startIdx: BigNumberish,
      endIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimReveal(
      location: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllRevealRequests(overrides?: CallOverrides): Promise<BigNumber>;

    getNRevealRequests(overrides?: CallOverrides): Promise<BigNumber>;

    getRevealRequest(
      location: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      coreAddress: string,
      planetHashKey: BigNumberish,
      spacetypeKey: BigNumberish,
      biomebaseKey: BigNumberish,
      perlinMirrorX: boolean,
      perlinMirrorY: boolean,
      perlinLengthScale: BigNumberish,
      _marketClosedCountdownTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestReveal(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rugPull(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BIOMEBASE_KEY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MARKET_CLOSE_COUNTDOWN_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PERLIN_LENGTH_SCALE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PERLIN_MIRROR_X(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERLIN_MIRROR_Y(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PLANETHASH_KEY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SPACETYPE_KEY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bulkGetRevealRequests(
      startIdx: BigNumberish,
      endIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimReveal(
      location: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllRevealRequests(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNRevealRequests(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRevealRequest(
      location: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      coreAddress: string,
      planetHashKey: BigNumberish,
      spacetypeKey: BigNumberish,
      biomebaseKey: BigNumberish,
      perlinMirrorX: boolean,
      perlinMirrorY: boolean,
      perlinLengthScale: BigNumberish,
      _marketClosedCountdownTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestReveal(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rugPull(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
